### ISSUE TITLE
Bug: A RenderFlex overflowed by 72 pixels on the bottom.

### ISSUE THREAD

**Issue by xiangxinyue** [IndustryBear/MentorApp#66]
**Describe the bug**
When I run the code to start, the error comes out.

An Observatory debugger and profiler on iPad Pro (12.9-inch) (4th generation) is available at: http://127.0.0.1:62230/FqFciAKtnwE=/
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during layout:
flutter: A RenderFlex overflowed by 72 pixels on the bottom.
flutter:
flutter: The relevant error-causing widget was:
flutter:   Column file:///Users/xinyuexiang/Desktop/MentorApp/lib/profile/user_profile.dart:87:22
flutter:
flutter: The overflowing RenderFlex has an orientation of Axis.vertical.
flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
flutter: This is considered an error condition because it indicates that there is content that cannot be
flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
flutter: like a ListView.
flutter: The specific RenderFlex in question is: RenderFlex#192ca relayoutBoundary=up7 OVERFLOWING:
flutter:   needs compositing
flutter:   creator: Column ← Center ← Padding ← Container ← _BodyBuilder ← MediaQuery ←
flutter:     LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
flutter:     AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#1b851 ink renderer] ← ⋯
flutter:   parentData: offset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=1234.0)
flutter:   size: Size(1024.0, 1234.0)
flutter:   direction: vertical
flutter:   mainAxisAlignment: start
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: center
flutter:   verticalDirection: down

**Expected behavior**
Do not have the yellow part.

**Screenshots**
<img width="712" alt="Screen Shot 2020-06-08 at 1 29 57 PM" src="https://user-images.githubusercontent.com/44979399/84073885-de678d80-a98e-11ea-9655-6c191c3e0b2c.png">

**Smartphone (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (4th generation)
 - But I tested the different device sizes such as iPhone 8 plus and iPhone 11.

**Comment by xiangxinyue** [comment]
Pro Tip : Whenever we are using text input, it is better to wrap it around a ListView to prevent rendering error when the soft keyboard shows up due to overflow pixels.

**Comment by xiangxinyue** [comment]
@override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter login demo'),
        ),
        body: Stack(
          children: <Widget>[
            showForm(),
            showCircularProgress(),
          ],
        ));
  }

**Comment by eivenlour** [comment]
This bug has been fixed in #67.
